### ISSUE TITLE
Referre crashes when player gets red card

### ISSUE THREAD

**Issue by SammyRamone** [RoboCup-Humanoid-TC/webots#159]
**Describe the Bug**
If a player gets a red card, the referee crashes.

**Steps to Reproduce**
1. Make robot get red card
2. See log

**Screenshots**
`Traceback (most recent call last):
  File "referee.py", line 2371, in <module>
    send_penalties()
  File "referee.py", line 1517, in send_penalties
    send_team_penalties(red_team)
  File "referee.py", line 1502, in send_team_penalties
    robot.loadState('__init__')
AttributeError: 'NoneType' object has no attribute 'loadState'
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at controller.net.AutoRefServer.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:829)`

The issue comes from this line https://github.com/RoboCup-Humanoid-TC/webots/blob/fea6a56146d2458439cdacfa889d9a920574dfd1/projects/samples/contests/robocup/controllers/referee/referee.py#L991-L994
Later the error is then thrown in https://github.com/RoboCup-Humanoid-TC/webots/blob/fea6a56146d2458439cdacfa889d9a920574dfd1/projects/samples/contests/robocup/controllers/referee/referee.py#L1504
Where robot was set here https://github.com/RoboCup-Humanoid-TC/webots/blob/fea6a56146d2458439cdacfa889d9a920574dfd1/projects/samples/contests/robocup/controllers/referee/referee.py#L1479

**Comment by SammyRamone** [comment]
I did not have the newest version of the referee. Seems to work now.
